### ISSUE TITLE
API access to information (user login & events)

### ISSUE THREAD

**Issue by McIntireEvan** [fuseumass/dashboard#203]
Hello! For Bitcamp, we just recently starting using dashboard. As part of our overall tech stack, we have a mobile app. Our previous registration application doubled as a backend, and we would pull user information and events directly from that app to use in our mobile app, and a few other places. We're trying to make dashboard fit the same use case, but we're running in to a few spots where either the feature doesn't exist, or I'm missing it.

1. API access to events - it would be great if there was a JSON endpoint to hit that would return all of the events.
2. Logging in from other sources - as I said, we'd like for users to be able to log in through the mobile app. From some research, I can see you all use devise, which unfortunately I'm not too familiar with. From my research and some playing around, I saw `devise-token-auth` as a method towards this end, but I'm unfamiliar with dashboard's implementation and use of it.

If I could at least get some pointers about how to hack these in, that would be very greatly appreciated.

Thanks for all the hard work!

**Comment by jwoglom** [comment]
Hey Evan, nice to hear from you. The first thing you asked about should already exist: we use it currently for our public facing schedules (i.e. https://hackher413.org/schedule). The route is just /events.json. It has no authentication since the assumption is that schedule info is public anyway. 

As for building a mobile app that authenticates with Dashboard, this should definitely be possible, we just haven't done any work on this front as of yet. I'll let some other folks chime in to this thread with thoughts of how we can work to include this in dashboard. (I'm primarily a Django rather than a Rails guy, so besides pointing you at devise I don't have many other suggestions.)

Happy to hear that you're interested in Dashboard -- while you're here, feel free to check out HackerForce (which serves a different need) as well. :)

**Comment by ikhatri** [comment]
Hey @McIntireEvan it's so awesome that you guys are using dashboard. As @jwoglom mentioned earlier, we already have an events API and just to point you to a few more helpful resources:
1. This is the link to the public hackumass endpoint: https://dashboard.hackumass.com/events.json
2. This is the javascript for generating a public facing schedule like James linked above, it uses the events API: https://hackumass.com/assets/js/schedule.js

Regarding the login API and mobile app integration. We actually had a mobile app under development in the past, and there was super old code for having a login API, but it was scrapped as we focused our tech resources to maintaining and expanding the web-application. We might be able to dig it up from an old branch somewhere, but it's probably on an outdated version of both rails and devise so my recommendation would be that you just roll your own. I don't know if our tech team will have the bandwidth to do it before your event, but if you do end up integrating the `devise-token-auth` gem, definitely submit a PR! Personally I think it'd be super sick if we could support sharing accounts between hackerforce & dashboard or something like that.

Also not completely related, but as I know the token auth uses oauth under the hood @abhinavtripathy I know was previously looking into adding MyMLH integration via OAuth as suggested in #148 

Finally (and I realize this is getting a bit lengthy) if you have any feedback from your experience setting up or using dashboard, please let us know! We'd love to hear from you :)

**Comment by McIntireEvan** [comment]
Thanks a bunch for the help! Great to see that the first bit already exists - I'll certainly keep you all updated on if I can get token login working. As for other feedback, are GH issues good, or is there another method that you all would like?

Thanks again!

**Comment by McIntireEvan** [comment]
I actually got something working, I think! The only caveat is that it has to be in a new namespace, as to not interfere with the current devise setup. Then, `user_is_authenticated?` from `application_controller` fails, due to `paths = [new_user_registration_path, hardware_items_path(:json), events_path(:json)]`, I think since hardware and events are not mounted in that same namespace. I'll make a PR soon with the other additions, but do you all have any suggestions on how to reconcile that, that fits with your current design?

**Comment by ikhatri** [comment]
Hey @McIntireEvan github issues is a great place for feedback! I believe you're correct about that. The reason for those two being mounted differently is actually because the `hardware_items` and `events` are both public APIs (they can be found at `/events.json` and `/hardware_items.json`). I believe the issue is that we basically just hacked around devise to make those APIs public, and I'm not sure what the best way to go forward is. @CodyRichter @abochnak @stevenlaitran any thoughts?
