### ISSUE TITLE
Local Deployment

### ISSUE THREAD

**Issue by jonathan-lei** [fuseumass/dashboard#232]
Hello!

I'm helping to host a hackathon called Hack3. 
Is it possible to deploy the dashboard in production locally, and if so, how?

Sponsors have provided free virtual machines, and we'd like to harness that rather than using another hosting service. 

Jonathan

**Comment by CodyRichter** [comment]
Hi Johnathan!

Thanks for reaching out to us with this question. Since Dashboard is just a Ruby on Rails application at heart, it definitely is possible to deploy it locally in a VM. Before going any further with this, I'd like to emphasize how much simpler it is to use Heroku than to do a local deployment. Heroku is extremely affordable (under $10/mo) and will streamline the process.

With that said, I can give you some resources to point you in the right direction for setting up Dashboard on a VM. Assuming you have an Ubuntu server, this is a pretty nice guide from Digital Ocean on how to get setup with a Rails app. You don't need to be using one of their droplets to follow the instructions, just any Ubuntu 18.04+ server: [Digital Ocean Rails Deployment Guide](https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-passenger-and-nginx-on-ubuntu-14-04 )

If you have any questions, or would like to reach out to us for assistance in getting Dashboard set up, just send us an email at team@hackumass.com and we can schedule a time to meet.

Best of luck!
