### ISSUE TITLE
No account options page for resetting password

### ISSUE THREAD

**Issue by Chriscbr** [fuseumass/dashboard#234]
When I visit dashboard.hackumass.com logged in, there is no option for me to change my password. If I click on my account name/icon on the top-right corner of the page, my only option is to log out. Perhaps this is only available to attendees? Either way this should be an option for users.

**Comment by CodyRichter** [comment]
Hey @Chriscbr 

Thanks for making this issue on our Github page! The version of Dashboard that is deployed for HackUMass right now is out-of-date, and we have since added that feature to newer versions. If you’d like to see a site which has the password change feature up and running, check out the [Dashboard for HackHer413](https://dashboard.hackher413.com)!

If you have any more issues or questions, please don’t hesitate to reach out and we’d be happy to take a look at them!
