### ISSUE TITLE
Fix mail service error 

### ISSUE THREAD

**Issue by vjawahar** [fuseumass/dashboard#290]
- Debug high bounce rate and restart mail service so that applicants get an email when they are accepted/RSVP

**Comment by AVS1508** [comment]
The bounce rate has been constant at 5.87% (i.e. no more bounces anymore) since our removal of an event application by a non-existent user. The pattern has been observed over 96 hours, thus, it is safe to see that the issue is resolved and the mail service has been restarted successfully. The views of the bounce rate and the sends are as follows:

### Bounce Rate View
<img width="697" alt="AWS SES Bounce Rate" src="https://user-images.githubusercontent.com/20084950/198849513-5b2815a8-6f26-49b9-9453-166eedb182c3.png">

### Sends View
<img width="699" alt="AWS SES Sends" src="https://user-images.githubusercontent.com/20084950/198849514-f81a7d06-3867-4e06-b5bb-652a0036ece3.png">
